version: "3"

services:
  browser:
    image: selenium/standalone-chrome:116.0
    restart: always
    environment:
      SE_VNC_NO_PASSWORD: 1
    # password: secret
    ports:
      - 7900:7900
      - 4444:4444
    shm_size: 2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      # - ./volumes:/app/volumes
      # - ./logs:/app/logs
      - .:/app:rw
    depends_on:
      browser:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8899/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 1
    #   start_period: 1s